# ElasticNet:
#   alpha: 0.2
#   l1_ratio: 0.5

models:
  Linear Regression: LinearRegression()
  K-Neighbors Regressor: KNeighborsRegressor()
  Decision Tree: DecisionTreeRegressor()
  Random Forest Regressor: RandomForestRegressor()
  XGBRegressor: XGBRegressor()
  CatBoosting Regressor: CatBoostRegressor(verbose=False)
  AdaBoost Regressor: AdaBoostRegressor()
  Gradient Boosting: GradientBoostingRegressor()
  ElasticNet: ElasticNet()